"""
Simple script to test sending of outbound e-mail via SMTP, initially via LCN
but then via Amazon SES...
"""

import smtplib
import logging
import email.message
import argparse
import datetime
import uuid

if __name__ == '__main__':
    ap = argparse.ArgumentParser(description='Test of SMTP mail')
    ap.add_argument('--server',       help = 'Name or IP address of SMTP server', default = 'email-smtp.eu-west-1.amazonaws.com')
    ap.add_argument('--username',     help = 'SMTP username', default = 'AKIAJCAQC2SGCUI3D3KA')
    ap.add_argument('--password',     help = 'SMTP password', default = 'Auq87Zy3r4GvQVN1z5W/ChzmbCQAiu7ANh8Olt28Wgst')
    ap.add_argument('--from-address', help = 'MAIL FROM address', default = 'mailbot@rotwang.org')
    ap.add_argument('--recipient',    help = 'E-mail address of recipient', default = 'snowy@verklempt.org')
    args = ap.parse_args()

    logging.basicConfig(level=logging.DEBUG)
    logging.info('Attempting to connect as {username}@{server}:{password}'.format(**vars(args)))

    message = email.message.EmailMessage()
    message['From'] = args.from_address
    message['Subject'] = 'test message'
    message['To'] = args.recipient
    message['Date'] = email.utils.formatdate()
    message['Message-ID'] = email.utils.make_msgid()
    message.set_content('This is a test e-mail message generated by the ConnexOne mailbot at {}\nYour UUID is {}'.format(datetime.datetime.now(), uuid.uuid4()))

    server = smtplib.SMTP(args.server, 587)
    server.starttls()
    server.login(args.username, args.password)
    server.send_message(message, args.from_address, args.recipient)