"""
Simple script to test sending of outbound e-mail via SMTP, initially via LCN
but then via Amazon SES...
"""

import smtplib
import logging
import email.message
import argparse
import datetime

if __name__ == '__main__':
    ap = argparse.ArgumentParser(description='Test of SMTP mail')
    ap.add_argument('server',    help='Name or IP address of SMTP server')
    ap.add_argument('username',  help='SMTP username')
    ap.add_argument('password',  help='SMTP password')
    ap.add_argument('recipient', help='E-mail address of recipient')
    args = ap.parse_args()

    logging.basicConfig(level=logging.DEBUG)
    logging.info('Attempting to connect as {username}@{server}:{password}'.format(**vars(args)))

    message = email.message.EmailMessage()
    message['Subject'] = 'test message'
    message['To'] = args.recipient
    message['Date'] = email.utils.formatdate()
    message['Message-ID'] = email.utils.make_msgid()
    message.set_content('This is a test e-mail message generated by the ConnexOne mailbot {}'.format(datetime.datetime.now()))

    server = smtplib.SMTP(args.server, 465)
    server.starttls()
    server.login(args.username, args.password)
    server.send_message(message, args.username, args.recipient)